spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trademark?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
mybatis:
  mapper-locations: mapper/*.xml
aliyun:
  accessKeyId: LTAI4GHyM4omK59SbtSiX8em
  accessKeySecret: Y98IOWRB2MTaUpm5XvaTpW4OM82CC1
  bucketName: enzo-trademark-bucket
  endpoint: oss-cn-beijing.aliyuncs.com
  urlPrefix: enzo-trademark-bucket.oss-cn-beijing.aliyuncs.com/
